apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  catalog.kubestack.com/heritage: kubestack.com/catalog/elasticsearch
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: elasticsearch
  app.kubernetes.io/version: v0.3.0
images:
- name: upmcenterprises/elasticsearch-operator
  newTag: 0.3.0
kind: Kustomization
resources:
- controller.yaml
