apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonAnnotations:
  app.kubernetes.io/version: v1.6.2
  catalog.kubestack.com/heritage: kubestack.com/catalog/postgresql
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: postgresql
resources:
- postgres-operator.yaml
- configmap.yaml
images:
- name: registry.opensource.zalan.do/acid/smoke-tested-postgres-operator
  newName: registry.opensource.zalan.do/acid/postgres-operator
  newTag: v1.10.1
